---
title: "Proposal writing: Study designs" 
author:   
  - Deependra Dhakal 
institute:   
  - GAASC, Baitadi
  - Tribhuwan University 
date: Academic year 2019-2020 
output:   
  beamer_presentation:  
    incremental: false  
    theme: "Frankfurt"  
    colortheme: "beaver"  
    fonttheme: "structuresmallcapsserif"
    toc: true   
    slide_level: 3
    fig_width: 5  
    fig_height: 4  
    fig_caption: true  
    highlight: tango
    keep_tex: true
    # includes:
    #   in_header: beamer_header.tex
classoption: "aspectratio=169"
link-citations: yes  
urlcolor: red  
linkcolor: red  
citecolor: blue
---

```{r setup, include=FALSE}
library(knitr)
require(tidyverse)
require(agricolae)
set.seed(453)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE, 
                      message = FALSE, warning = FALSE,
                      out.width = "70%", fig.width = 6)
options(knitr.table.format = "latex")
options(knitr.kable.NA = "", digits = 2)
options(kableExtra.latex.load_packages = FALSE)
# require(plantbreeding) #install first
# require(agridat)
```

# Popular design variants

### RCB design

```{r rcb-design}
trt<-1:6
t <- length(trt)
r <- 4
outdesign <- design.rcbd(trt, r = 4, randomization = T, serie = 1)
outdesign$book <- outdesign$book %>% 
        mutate(row = rep(seq_along(1:6), times = 4),
               col = block)

desplot::desplot(trt~row*col|block, data = outdesign$book, 
                 out1 = row, out2= col, flip = TRUE,
                 layout = c(3, 1), 
                 gg = TRUE,
                 text = trt, cex = 0.8, show.key = FALSE,
                 out1.gpar=list(col = "black", lwd = 1), 
                 out2.gpar=list(col = "black", lwd = 0.6),
                 # out2.gpar=list(col = "darkblue", lwd = 1, lty = 1), 
                 main = "Field plot layout in RCB design\n Number of treatments = 6, Replication = 4")

```

### Alpha lattice design

```{r alphamod-function}
design.alpha_mod <- function (trt, k, r, serie = 2, seed = 0, kinds = "Super-Duper", 
          randomization = TRUE) 
{
  number <- 10
  if (serie > 0) 
    number <- 10^serie
  name.trt <- c(paste(deparse(substitute(trt))))
  ntr <- length(trt)
  if (seed == 0) {
    genera <- runif(1)
    seed <- .Random.seed[3]
  }
  set.seed(seed, kinds)
  s <- ntr/k
  if (ntr%%k != 0) 
    cat("\nThe size of the block is not appropriate", "\nthe number of treatments must be multiple of k (size block) \n")
  else {
    serie <- ""
    if (r == 2 & k <= s) {
      alpha <- matrix(0, nrow = k, ncol = r)
      alpha[2, 2] <- 1
      for (i in 3:k) {
        alpha[i, 2] <- alpha[i - 1, 2] + 1
      }
      serie <- "I"
    }
    if (r == 3 & s%%2 != 0 & k <= s) {
      alpha <- matrix(0, nrow = k, ncol = r)
      alpha[2, 2] <- 1
      alpha[2, 3] <- s - 1
      for (i in 3:k) {
        alpha[i, 2] <- alpha[i - 1, 2] + 1
        alpha[i, 3] <- alpha[i - 1, 3] - 1
      }
      serie <- "II"
    }
    if (r == 3 & s%%2 == 0 & k < s) {
      s1 <- s/2
      alpha <- matrix(0, nrow = k, ncol = r)
      alpha[2, 2] <- 1
      alpha[2, 3] <- s1
      for (i in 3:k) {
        alpha[i, 2] <- alpha[i - 1, 2] + 1
        alpha[i, 3] <- alpha[i - 2, 3] + 1
      }
      serie <- "III"
    }
    if (r == 4 & s%%2 != 0 & s%%3 != 0 & k <= s) {
      s2 <- (s + 1)/2
      alpha <- matrix(0, nrow = k, ncol = r)
      alpha[2, 2] <- 1
      alpha[2, 3] <- s - 1
      alpha[2, 4] <- s2
      for (i in 3:k) {
        alpha[i, 2] <- alpha[i - 1, 2] + 1
        alpha[i, 3] <- alpha[i - 1, 3] - 1
        alpha[i, 4] <- alpha[i - 2, 4] + 1
      }
      serie <- "IV"
    }
    if (serie == "") {
      cat("\nhelp(design.alpha): to see the series of alpha generators\n")
      stop
    }
    else {
      nf <- nrow(alpha)
      nc <- ncol(alpha)
      cc <- rep(alpha[, 1], s)
      for (i in 2:r) {
        cc <- c(cc, rep(alpha[, i], s))
      }
      dim(cc) <- c(nf, s, r)
      for (m in 1:r) cc[, 1, m] <- alpha[, m]
      for (i in 2:s) {
        for (j in 1:nf) {
          for (m in 1:r) {
            cc[j, i, m] <- cc[j, i - 1, m] + 1
            if (cc[j, i, m] >= s) 
              cc[j, i, m] <- 0
          }
        }
      }
      for (j in 1:nf) {
        cc[j, , ] <- cc[j, , ] + (j - 1) * s
      }
      intermediate <- cc
      E <- (ntr - 1) * (r - 1)/((ntr - 1) * (r - 1) + r * 
                                  (s - 1))
      parameters <- list(design = "alpha", trt = trt, k = k, 
                         r = r, serie = serie, seed = seed, kinds = kinds)
      statistics <- data.frame(treatments = ntr, blocks = s, 
                               Efficiency = E)
      rownames(statistics) <- "values"
      for (m in 1:r) {
        for (j in 1:s) {
          aleatorio <- 1:k
          if (randomization) 
            aleatorio <- sample(1:k, k)
          cc[, j, m] <- cc[aleatorio, j, m]
        }
      }
      for (m in 1:r) {
        aleatorio <- 1:s
        if (randomization) 
          aleatorio <- sample(1:s, s)
        cc[, , m] <- cc[, aleatorio, m]
      }
      cc <- cc + 1
      block <- gl(s, k)
      md <- as.numeric(cc[, , 1])
      bp <- 1:ntr
      if (randomization) 
        bp <- sample(1:ntr, ntr)
      trt <- trt[bp]
      mtr <- trt[md]
      book <- data.frame(block = as.factor(block), trt = as.factor(mtr), 
                         replication = 1)
      for (i in 2:r) {
        md <- as.numeric(cc[, , i])
        mtr <- trt[md]
        book1 <- data.frame(block = as.factor(block), 
                            trt = as.factor(mtr), replication = i)
        book <- rbind(book, book1)
      }
      Rep <- book$replication
      plots <- Rep * number + (1:ntr)
      cols <- as.numeric(rep(gl(k, 1), s * r))
      book <- data.frame(plots = plots, cols = cols, book)
      book <- data.frame(row.names = NULL, book)
      book$block <- gl(s * r, k)
      book[, 2] <- as.factor(book[, 2])
      book[, 5] <- as.factor(book[, 5])
      names(book)[4] <- name.trt
      tr <- as.character(book[, 4])
      dim(tr) <- c(k, s, r)
      if (r == 2) 
        design <- list(rep1 = t(tr[, , 1]), rep2 = t(tr[, 
                                                        , 2]))
      if (r == 3) 
        design <- list(rep1 = t(tr[, , 1]), rep2 = t(tr[, 
                                                        , 2]), rep3 = t(tr[, , 3]))
      if (r == 4) 
        design <- list(rep1 = t(tr[, , 1]), rep2 = t(tr[, 
                                                        , 2]), rep3 = t(tr[, , 3]), rep4 = t(tr[, , 
                                                                                                4]))
      outdesign <- list(parameters = parameters, statistics = statistics, 
                        sketch = design, book = book)
      return(outdesign)
    }
  }
}
```


```{r alpha-design}
trt<-1:25
t <- length(trt)
# size block k
k<-5
# Blocks s
s<-t/k
# replications r
r <- 3
outdesign <- design.alpha_mod(trt, k = 5, r = 3, randomization = T, serie = 1)
desplot::desplot(trt~cols*block|replication, data = outdesign$book, 
                 out1 = block , layout = c(3, 1), out2 = cols,
                 text = trt, cex = 0.8, show.key = FALSE,
                 out1.gpar=list(col = "black", lwd = 2.5), 
                 # out2.gpar=list(col = "darkblue", lwd = 1, lty = 1), 
                 main = "Field plot layout in Alpha lattice design\n Number of treatments = 25, Block size = 6, Replication = 3")

```

### Split plot design

```{r nested-design, fig.width=8}
trt1 <- c("Carbendazim", "Mancozeb + Metalaxyl", "Fenamidone + Mancozeb", "Propiconazole", "Trichoderma", "Fenamidone")
trt2 <- c("Control", "Seed Treatment", "Foliar Spray", "Seed + Foliar")
splitplotr3t1t2 <- design.split(trt1, trt2, r = 3, serie = 2, seed = 234)
split_field <- splitplotr3t1t2$book
split_field <- cbind(split_field, mainplot = as.factor(c(rep(1:18, each = 4))))

desplot::desplot(form = trt1 ~ mainplot*splots|block, 
        out1 = trt1 , out2 = trt2, data = split_field, layout = c(3, 1),
        text = trt2, cex = 0.8, 
        out1.gpar=list(col = "black", lwd = 2), 
        out2.gpar=list(col = "darkblue", lwd = 1, lty = 1), 
        main = "Field plot layout in Split plot design\n Main plots = 4, Sub plots = 6, Replication = 3")
```
