---
title: Writing academic paper
author: Deependra Dhakal
date: \today
classoption: compress
toc: true
output: binb::monash
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, 
                      cache=TRUE, dev.args=list(bg=grey(0.9), pointsize=11))
```

# The Paper

## Background

- If you are working in academics you will need to write some papers. 
- The primary signal to most traditional academic communities still remains published peer-reviewed papers
- No one ever feels comfortable enough to try to write one

## Why write anyway

- Even if you aren't going to be in academics, papers are a great way to show off that you can 

  (a) identify a useful project, 
  (b) finish a project, and
  (c) write well.
  
- So, when to write your first academic paper?

  - \alert{As soon as possible!}

## Purpose of joining a graduate program (in some order)

- Freedom
- Time to discover new knowledge
- Time to dive deep
- Opportunity for leadership
- Opportunity to make a name for yourself
- Papers
- Blogs
- Get a job

## What is an academic paper?

- A scientific paper can be distilled into four parts:

  1. A set of methodologies
  1. A description of data
  1. A set of results
  1. A set of claims
    
## What an academic paper is for?

- When you (or anyone else) writes a paper the goal is to communicate clearly items 1-3 so that they can justify the set of claims you are making. 
- Before you can even write down 4 you have to do 1-3. 
- So that is where you start when writing a paper.

# The problem

## Deal with it

- You decide on a problem to work (role of your advisor!)
- Make the problem yours!
- Hopefully problem should be such where you are just insanely curious to know the answer at the end, to the point where you just have to figure it out and kind of don't care what the answer is. 

## Your first project ideally is

- Concrete
- Solves a scientific problem
- Gives you an opportunity to learn something new
- Something you feel ownership of
- Something you want to work on

# The research

## How to redo a search ?

- Once you _have a problem_ the next step is to actually do the research. 
- Basic idea of an analytical research is:

  - Define the question
  - Get the data
  - Explore the data
  - Build/borrow a model
  - Perform the analysis
  - Check/critique results
  - Write things up

## Stop doing anyting and start writing

- Work own your internal timer that tells you, "ok we have done enough, time to write this up". 
- This is one of the hardest things to learn, but if you are going to stay in academics it is a critical skill.
- What are the choices ?

  - \alert{None}

## Scenario 1 and 2

- If you started with a very concrete question at the beginning then once you have done enough analysis to convince yourself that you have the answer to the question. If the answer to the question is interesting/surprising then it is time to stop and write.

- If the answer isn't interesting/surprising but you started with a concrete question it is also time to stop and write.

## Scenario 3

- If you started with a question that wasn't so concrete then it gets a little trickier. The basic idea here is that you have convinced yourself you have a result that is worth reporting. This is the recipie for two or more papers not just one.

## How do you start writing?

- Once you have a set of results and are ready to start writing up the paper the first thing is not to write. 
- Instead think about presenting it in the best possible scientific way.
- \alert{The perfect is the enemy of the very good.}

# What sections does a paper constitute?

## Title 

- Should be very short, no colons if possible, and state the main result. 
- Example, "Diverse toolboox of cereal germplasm helps solve climate crisis". 
- Here you want to make sure people will read the paper without overselling your results - this is a delicate balance.
    
## Abstract

- In (ideally) 4-5 sentences explain: 
  
  (a) what problem you are solving, 
  (b) why people should care, 
  (c) how you solved the problem, 
  (d) what are the results and
  (e) use case of the solution, if you came up with

## Introduction

- A more lengthy (1-3 pages) explanation of the problem you are solving 
- Why people should care, 
- How you are solving it. 
- Review what other people have done in the area. 
- The most critical thing is never underestimate how little people know or care about what you are working on. It is your job to explain to them why they should.

## Methods 

- You should state and explain your statistical process,
- What the parameters are, how you chose them, 
- Any strengths or weakenesses of your proposed approach.
- Compare your proposed approach to the state of the art methods.
- An example analysis: It is good to have one compelling "use case" laid out from the beginning to the end.

## Conclusions

- Summarize what you did and explain why what you did is important one more time. 
- Provide a link to the adaptation of your work or the original work you adapted and improved upon.

# Writing in general

## The length

- The length of the paper will depend a lot on which journal you are targeting. 
- In general the shorter/more concise the better. 
- This means most papers will be in the 4-15 page range, but with a huge variance.
- An analysis paper may present the analysis/results you are doing first and move all of the methods and comparisons to after (or to the supplement).

## The accomplishment

- The first draft should be as complete as you think you can make it. 
- Ideally this is something you think you could submit. 
- If it's your first paper it is almost never ready to submit. Dont feel bad about this.
- Write with a partner to make quick progress later on

## The submission

- The stage that fruits.
- When you submit a paper you will feel this huge sense of accomplishment and relief. You should!!
- Once your paper is accepted you get to celebrate, hooray!!!!

# The upshot

## Developing a style

- Scientific papers are written in a particular style. 
- The best way to learn how to read these papers is to go to some journals that regularly publish good papers like Euphytica or Plant Breeding Journal and read a ton of papers.
- Whenever you can, write in plain English and make the approach you are using understandable and clear.
- Learn by mimicking the styles of other people. As with any writing, the more you read, the better a writer you will be.
